version: "3"
services:
  redis:
    image: redis:6.2.5
    container_name: redis_auto
    ports:
      - "6379:6379"
    volumes:
      - /home/app/redis/data:/data
      - /home/app/redis/conf/redis.conf:/etc/redis/redis.conf
    expose:
      - "6379"
    command:
      - "redis-server"
      - "/etc/redis/redis.conf"
      - "--appendonly"
      - "yes"
      - "--requirepass"
      - "123456"
      - "--bind"
      - "0.0.0.0"
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  autotest_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: autotest_backend:1.0.0
    container_name: autotest
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn -D -c gunicorn.py autotest_backend.wsgi:application && export C_FORCE_ROOT=True  && celery -A autotest_backend worker -l info -P eventlet"
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: "service_started"
    expose:
      - "8000"
    links:
      - redis:myredis
    restart: always
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_DB=autotest_backend
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_PORT=3306
      - REDIS_HOST=myredis
      - REDIS_PASSWORD=123456
      - REDIS_PORT=6379


  nginx:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx_auto
    ports:
      - "88:88"
    depends_on:
      autotest_backend:
        condition: "service_started"
    expose:
      - "88"
    links:
      - autotest_backend:myweb
    restart: always
    command: ["nginx", "-g", "daemon off;"]


