version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=autotest_backend
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  redis:
    build:
      context: ./conf/redis
      dockerfile: Dockerfile
    image: redis
    container_name: redis_auto
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/redis/data:/data
    expose:
      - "6379"
    command: [
       'redis-server /etc/redis/redis.conf',
       '--appendonly yes',
       '--requirepass 123456',
       '--bind 0.0.0.0'
    ]
    restart: always


  autotest_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: autotest_backend:1.0.0
    container_name: autotest
    command: /bin/bash -c "python manage.py makemigrations && python manager.py migrate && gunicorn -c gunicorn.py autotest_backend.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    links:
      - db:mydb
      - redis:myredis
    restart: always
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_DB=autotest_backend
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_PORT=3306
      - REDIS_HOST=myredis
      - REDIS_PASSWORD=123456
      - REDIS_PORT=6379


  nginx:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx_auto
    ports:
      - "88:88"
    depends_on:
      - autotest_backend
    expose:
      - "88"
    links:
      - autotest_backend:myweb
    restart: always
    command: ["nginx", "-g", "daemon off;"]


