# Generated by Django 4.1 on 2023-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=256, verbose_name='环境名称')),
                ('agreement', models.SmallIntegerField(choices=[(0, 'http'), (1, 'https')], verbose_name='协议')),
                ('hosts', models.CharField(max_length=256, verbose_name='域名或ip')),
                ('port', models.CharField(max_length=64, verbose_name='端口号')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='简要说明')),
                ('enable_flag', models.SmallIntegerField(blank=True, choices=[(0, '失效'), (1, '生效')], null=True, verbose_name='有效标识')),
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='更新人')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试环境表',
                'verbose_name_plural': '测试环境表',
            },
        ),
    ]
